# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


# Navieras
[ "Seleccione Naviera ...",
"ACL",
"Alianca",
"ANL",
"APL",
"Arkas",
"Atlanticargo",
"Balaji Shipping",
"Beacon Intermodal",
"Blue Sky",
"Bridgehead",
"CAI",
"Canadian National Railway",
"Canadian Pacific Railway",
"CCNI",
"CHINA SHIPPING",
"CMA CGM",
"CNC Line",
"COSCO",
"Cronos",
"Crowley",
"CSAV NORASIA",
"DAL",
"Delmas",
"Dong Fang International Investment",
"Emirates Shipping Line",
"EVERGREEN",
"Florens container services",
"GESeaCo",
"GOLD",
"Gold Star Line",
"Grimaldi",
"Hamburg Sud",
"Hanjin Shipping",
"HAPAG (HL)",
"Heung-A Shipping",
"HYUNDAI",
"ITALIA MARITTIMA",
"K-LINE",
"Korea Marine Transport",
"Libra",
"Linea Messina",
"MAERSK",
"MAG shipping",
"Marfret",
"Matson",
"MOL",
"MSC",
"Namsung",
"NSCSA",
"NYK Line",
"OOCL",
"OTAL",
"Pacific Direct Line",
"PIL",
"Pollux & Castor",
"RCL",
"Royal Arctic",
"Safmarine",
"SCI",
"Seaboard Marine",
"SeaCastle Inc, (Interpool)",
"Sea Star Line",
"SENATOR LINES",
"Sinokor Merchant Marine",
"SITC",
"Sofrana Unilines",
"Star Shipping",
"STX Pan Ocean",
"TAL International",
"Tarros",
"Textainer",
"Triton Container",
"Turkon",
"UES",
"United Arab Shipping",
"Wan Hai Lines",
"Waterfront Container",
"YANG MING (YML)",
"ZIM"
  ].each do |valor|
  Mantenedor.create(:tipo => :naviera, :valor => valor)
end